[package]
name = "embed-search"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11"

# Nomic Embed GGUF support
reqwest = { version = "0.11", features = ["stream"] }
dirs = "5.0"
memmap2 = "0.9"

# For actual GGUF inference (optional - comment out if build fails)
# llama-cpp-rs = { version = "0.2", features = ["static"] }

# LanceDB vector database  
lancedb = "0.21.2"
arrow = "55.0"
arrow-array = "55.0" 
arrow-schema = "55.0"

# Legacy sled for migration
sled = "0.34"

# Always needed
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.43", features = ["full"] }
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
once_cell = "1.19"

# Configuration management
toml = "0.8"
config = "0.13"
clap = { version = "4.4", features = ["derive"] }

# Embedding optimization
lru = "0.12"
sha2 = "0.10"

# Native search and parallel processing
rayon = "1.7"
walkdir = "2.4"

# Retry logic with exponential backoff
backoff = "0.4"

# Memory management and system monitoring
sysinfo = "0.30"

# Observability - metrics and logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono"] }

# Tree-sitter for symbol indexing
tree-sitter = "0.23"
tree-sitter-rust = "0.23"
tree-sitter-python = "0.23"
tree-sitter-javascript = "0.23"
tree-sitter-typescript = "0.23"
tree-sitter-go = "0.23"
tree-sitter-java = "0.23"
tree-sitter-c = "0.23"
tree-sitter-cpp = "0.23"
# Commented out tree-sitter dependencies with version issues
# tree-sitter-c-sharp = "0.20"
# tree-sitter-ruby = "0.20"
# tree-sitter-php = "0.20"
# tree-sitter-swift = "0.20"
# tree-sitter-kotlin = "0.3"
# tree-sitter-scala = "0.20"
tree-sitter-html = "0.23"
tree-sitter-css = "0.23"
tree-sitter-json = "0.23"
# tree-sitter-yaml = "0.5"
# tree-sitter-toml = "0.5"
# tree-sitter-xml = "0.22"
# tree-sitter-sql = "0.0.2"
tree-sitter-bash = "0.23"
# tree-sitter-lua = "0.1"
# Note: These tree-sitter languages have different version numbers
# tree-sitter-elixir = "0.3"
# tree-sitter-ocaml = "0.22" 
# tree-sitter-haskell = "0.15"
# tree-sitter-zig = "1.0"

[features]
default = []

[dev-dependencies]
criterion = "0.5"
tempfile = "3.12"

[[bench]]
name = "line_tracking_bench"
harness = false

[[test]]
name = "chunker_integration_tests"
path = "tests/chunker_integration_tests.rs"

[[test]]
name = "line_tracking_tests"
path = "tests/line_tracking_tests.rs"

[[test]]
name = "vectortest_line_tracking"
path = "tests/vectortest_line_tracking.rs"

[[test]]
name = "three_chunk_stress_test"
path = "tests/three_chunk_stress_test.rs"

[[test]]
name = "task003_final_validation"
path = "tests/task003_final_validation.rs"

[[test]]
name = "nomic_embedding_tests"
path = "tests/nomic_embedding_tests.rs"

[[test]]
name = "vectortest_embedding_stress"
path = "tests/vectortest_embedding_stress.rs"

[[test]]
name = "vector_storage_tests"
path = "tests/vector_storage_tests.rs"

[[test]]
name = "vector_storage_similarity_tests"
path = "tests/vector_storage_similarity_tests.rs"

[[test]]
name = "comprehensive_stress_tests"
path = "tests/comprehensive_stress_tests.rs"

[[test]]
name = "real_embedding_system_tests"
path = "tests/real_embedding_system_tests.rs"

[[test]]
name = "embedding_performance_benchmark"
path = "tests/embedding_performance_benchmark.rs"

[[test]]
name = "symbol_indexing_tests"
path = "tests/symbol_indexing_tests.rs"

[[example]]
name = "embedding_optimization_demo"
path = "examples/embedding_optimization_demo.rs"

[[bin]]
name = "test_accuracy"
path = "src/bin/test_accuracy.rs"

[[bin]]
name = "fast_accuracy_test"
path = "src/bin/fast_accuracy_test.rs"

[[bin]]
name = "unbiased_accuracy_test"
path = "src/bin/unbiased_accuracy_test.rs"
