pub mod ripgrep;
pub mod native_search;
pub mod fusion;
pub mod unified;
pub mod preprocessing;
pub mod cache;
pub mod symbol_index;
pub mod symbol_enhanced_searcher;
pub mod tantivy_search;
pub mod search_adapter;
pub mod bm25;
pub mod text_processor;
pub mod inverted_index;

pub use ripgrep::{RipgrepSearcher, RipgrepTextSearcher, ExactMatch};
pub use native_search::{NativeSearcher, SearchMatch};
pub use fusion::{SimpleFusion, FusedResult, MatchType};
pub use unified::{UnifiedSearcher, SearchResult};
pub use preprocessing::QueryPreprocessor;
pub use cache::SearchCache;
pub use symbol_index::{SymbolIndexer, SymbolDatabase, Symbol, SymbolKind};
pub use tantivy_search::TantivySearcher;
pub use search_adapter::{TextSearcher, create_text_searcher, create_text_searcher_with_root};
pub use bm25::{BM25Engine, BM25Match, BM25Document, Token as BM25Token};
pub use text_processor::{CodeTextProcessor, ProcessedToken, TokenType};
pub use inverted_index::{InvertedIndex, DocumentMetadata};