[package]
name = "mcp-verification"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "verification"
path = "comprehensive_mcp_verification.rs"

[dependencies]
serde_json = "1.0"
tempfile = "3.0"